### ISSUE TITLE
Will it work on an A4000?

### ISSUE THREAD

**Issue by tingox** [Bloodmosher/Amiga-VideoSlot-RGBtoHDMI#11]
Neat project! Will it work in the video slot of an Amiga A4000?

**Comment by Bloodmosher** [comment]
No this is for A2000 and A3000 only.

**Comment by tingox** [comment]
aha, ok. Thanks for the feedback.

**Comment by ceztko** [comment]
But some video slot designed for A2000/A3000 could be plugged to A4000 as well, eg. A2320, so if this board just uses the normal non extended part of the video slot, it should work also on A4000 for non AGA only doubled modes (which use the extended part of the video slot with more color bit depth for pixels).
