### ISSUE TITLE
3.3v

### ISSUE THREAD

**Issue by levo-man** [Bloodmosher/Amiga-VideoSlot-RGBtoHDMI#4]
Not really an issue but why did you not le the raspberry pi give the 3.3v power?

**Comment by Bloodmosher** [comment]
Great question! c0pperdragon may have an answer on this- but based on what I could find, I suspect it is current draw related. There's some discussion on the topic of whether to power from the pi's 3.3v or something external here: https://www.raspberrypi.org/forums/viewtopic.php?t=284104
