### ISSUE TITLE
HDMI connector on A2000 rear bracket

### ISSUE THREAD

**Issue by matthiesenj** [Bloodmosher/Amiga-VideoSlot-RGBtoHDMI#6]
Hi,
I was wondering what type of HDMI connector/adapter you used for the bracket - the photo sort of indicates that it's mounted using screws, or is it just a generic C->A adapter glued in place?

**Comment by Bloodmosher** [comment]
It is screwed on, you can get them here:
https://www.amazon.com/gp/product/B071LDPR8H/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
